### ISSUE TITLE
Curl??

### ISSUE THREAD

**Issue by dynamitemedia** [Xeoncross/wnmp#2]
is this added?  if not can it be?  meant curl sorry!

**Comment by hurrycaner** [comment]
@dynamitemedia you can install windows version of git, in it's bin folder, you should find curl.exe (don't forget to copy the libraries with it, like libcrypto.dll and libssl.dll)

@Xeoncross for some ppl, that's still the best way to have a portable enviroment... this way i can get some nice and small web server to run with a good IDE on a low spec laptop (vagrant is too much for it and sometimes i'm not online)
